name: Build and Package Spring Boot App

on:
  push:
    branches:
      - main  # Change to your default branch
  pull_request:
    branches:
      - main  # Change to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Change to your required Java version
          distribution: 'adopt'

      - name: Set environment variable
        run: echo "SERVER_PORT=3000" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Download Launch4j
        run: |
          wget -q https://github.com/luchsh/launch4j/releases/download/launch4j-3.16/launch4j-3.16.zip
          unzip -q launch4j-3.16.zip -d launch4j

      - name: Create executable with Launch4j
        run: |
          cd launch4j
          ./launch4j ../launch4j-config.xml  # Update with the path to your configuration file

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            target/jar-exe-0.0.1-SNAPSHOT.jar  # Change this to match your jar file name
            launch4j/target/jarToExe.exe  # Change to your output exe name
