name: Build and Package Spring Boot App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '1.8'
          distribution: 'temurin''

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Download and Install Launch4j
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -L -o launch4j.tgz "https://excellmedia.dl.sourceforge.net/project/launch4j/launch4j-3/3.50/launch4j-3.50-linux-x64.tgz?viasf=1"
          tar -xzf launch4j.tgz
          sed -i -e 's/\r$//' launch4j/launch4j

      - name: Create executable with Launch4j
        run: |
          launch4j/launch4j config.xml

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            target/jar-exe-0.0.1-SNAPSHOT.jar
            target/jar.exe
